---
abstract: 'Split files of a directory to subdirectories'
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
build_requires:
  File::Temp: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dir-Split
provides:
  Dir::Split:
    file: lib/Dir/Split.pm
    version: 0.80_01
requires:
  Carp: '0'
  File::Basename: '0'
  File::Copy: '0'
  File::Find: '0'
  File::Path: '0'
  File::Spec: '0'
  Params::Validate: '0'
  boolean: '0'
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/stsc/Dir-Split
version: 0.80_01
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
